name: Angular CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint

      - name: Unit Tests
        run: yarn run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI

      - run: yarn run webdriver-update-ci

      - name: E2E Tests
        run: yarn run e2e -- --protractor-config=./e2e/protractor-ci.conf.js --webdriver-update=false

      - name: Build
        run: yarn run build

      - name: docker build
        uses: actions/docker/cli
        with:
          args: build -t 0.0.1 .

      - name: docker login
        uses: actions/docker/login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: docker push
        uses: actions/docker/cli
        with:
          args: push blackforestsolutions/locofrontendang
