name: Angular Continous Integration

on: [push, pull_request]

jobs:
  testAndBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Dependencies
        run: yarn install

      - name: Lint (Checkstyles)
        run: yarn run lint

      - name: Unit Tests
        run: yarn run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI

      - run: yarn run webdriver-update-ci

      - name: E2E Tests
        run: yarn run e2e -- --protractor-config=./e2e/protractor-ci.conf.js --webdriver-update=false

      - name: Build
        run: yarn run build --prod --aot --progress=false

      - name: Build latest Docker Image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/locofrontendang:latest

      - name: Login Dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        if: github.event.pull_request.head.ref == 'master'

      - name: Push latest Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/locofrontendang:latest
        if: github.event.pull_request.head.ref == 'master'
