name: Angular Continous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    - name: Checkout
        uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn run build --prod --aot --progress=false

    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/locofrontendang:latest
      if: github.event.pull_request == true

    - name: Login to DockerHub Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      if: github.event.pull_request == true

    - name: Push the latest Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/locofrontendang:latest
      if: github.event.pull_request == true
